ext {
    api_version_major = 13
    api_version_minor = 1
    api_version_patch = 5
    api_version_name = "${api_version_major}.${api_version_minor}.${api_version_patch}"
}
<provider
    android:name="rikka.shizuku.ShizukuProvider"
    android:authorities="${applicationId}.shizuku"
    android:multiprocess="false"
    android:enabled="true"
    android:exported="true"
    android:permission="android.permission.INTERACT_ACROSS_USERS_FULL" />

<!-- android:permission="android.permission.INTERACT_ACROSS_USERS_FULL" is to protect this provider from accessing by normal apps -->
